### ISSUE TITLE
AS lookup returns no data NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ProsperCraft** [Karanum/AdamantineShield#30]
Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3050
    Minecraft Forge: 14.23.3.2655

AdamantineShield-0.4.1.jar

[08:48:52] [Server thread/INFO] [nucleus]: Goshen ran the command: /as lookup
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.NoSuchElementException: No value present
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.Optional.get(Optional.java:135)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at com.karanumcoding.adamantineshield.lookup.BlockLookupResult.readResult(BlockLookupResult.java:27)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at com.karanumcoding.adamantineshield.lookup.LookupResult.<init>(LookupResult.java:23)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at com.karanumcoding.adamantineshield.lookup.BlockLookupResult.<init>(BlockLookupResult.java:17)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at com.karanumcoding.adamantineshield.commands.lookup.CommandLookup.lambda$execute$0(CommandLookup.java:63)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:48:54] [adamantineshieldPool-Thread-0/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:       at java.lang.Thread.run(Thread.java:748)

**Comment by ProsperCraft** [comment]
Oddly after I did some inspecting with /as i    I was able to use /as lookup

**Comment by Karanum** [comment]
Seems to have been some sort of database desync. Please let me know if the issue is recurring.
