### ISSUE TITLE
Block console spam

### ISSUE THREAD

**Issue by Whazaaaaa** [Karanum/AdamantineShield#34]
Hello,

I'm getting a lot of spam in my console of writes not going well.
Could you implement a simple config for it to not spam this on every .printStackTrace(). Or even better have a seperate logfile where it saves all these logs to use/fix at a later date?
something like:
`debugmode=print/log/none`
Or something else you can come up with.

Or better yet if you are able to fix why its catching, and thus spamming the console with stacktraces.

Forge: forge-1.12.2-14.23.4.2705-universal
Sponge: spongeforge-1.12.2-2705-7.1.0-BETA-3126
Ashield: AdamantineShield-0.4.1
Log of stacktrace: [admanantineshieldstacktrace.txt](https://github.com/Karanum/AdamantineShield/files/2050237/admanantineshieldstacktrace.txt)

Thank you for this plugin!

**Comment by Whazaaaaa** [comment]
Note that this is on a modpack. And its not with every block that this happens. Just some (probably odd) modded blocks. I have yet to find a proper one that causes the stacktrace. I'll investigate this further if needed.

**Comment by bucketphobia** [comment]
> [05:13:22] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=adamantineshield, name=AdamantineShield, version=0.4.1, description=Action logging and rollback plugin for Sponge, authors=[Karanum, Snootiful], source=/root/minecraft/./mods/plugins/AdamantineShield-0.4.1.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.event.cause.Cause.getContext()Lorg/spongepowered/api/event/cause/EventContext;
        at com.karanumcoding.adamantineshield.listeners.PlayerBlockChangeListener.onBreakCascade(PlayerBlockChangeListener.java:53) ~[PlayerBlockChangeListener.class:?]
        at org.spongepowered.common.event.listener.BreakListener_PlayerBlockChangeListener_onBreakCascade57.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) ~[SpongeModEventManager.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) ~[SpongeModEventManager.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) ~[SpongeImpl.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:627) ~[TrackingUtil.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.general.GeneralPhase.processBlockTransactionListsPost(GeneralPhase.java:164) ~[GeneralPhase.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.general.GeneralPhase.postDispatch(GeneralPhase.java:117) ~[GeneralPhase.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.general.PostState.unwind(PostState.java:58) ~[PostState.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.general.GeneralPhase.unwind(GeneralPhase.java:102) ~[GeneralPhase.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.TrackingUtil.performBlockAdditions(TrackingUtil.java:712) ~[TrackingUtil.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:614) ~[TrackingUtil.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:85) ~[BlockTickPhaseState.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:85) [BlockTickPhaseState.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:225) [CauseTracker.class:1.11.2-2476-6.1.0-BETA-2792]
        at org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:267) [TrackingUtil.class:1.11.2-2476-6.1.0-BETA-2792]
        at net.minecraft.world.WorldServer.redirect$onUpdateTick$zkg000(WorldServer.java:2236) [lw.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745) [lw.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

Copy of the error that shows up for me.

**Comment by johnfg2610** [comment]
do you have a list of mods you were running when this occurred or even better what block was broken? @OmarWazzan @Whazaaaaa
