### ISSUE TITLE
Incorrect string value for column 'data'

### ISSUE THREAD

**Issue by LemADEC** [Karanum/AdamantineShield#38]
As of AdamantineShield-0.4.1, an MariaDB SQL error is seen intermittently in the console:
```
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]: java.sql.SQLDataException: (conn:558707) Incorrect string value: '\xE2\x96\x8A\xE2\x97\xA5...' for column 'data' at row 1
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:148)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at com.karanumcoding.adamantineshield.db.queue.InventoryQueueEntry.writeToConnection(InventoryQueueEntry.java:53)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at com.karanumcoding.adamantineshield.db.DatabaseWriterTask.run(DatabaseWriterTask.java:28)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [com.karanumcoding.adamantineshield.db.DatabaseWriterTask:run:32]:         at java.lang.Thread.run(Thread.java:748)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.sql.SQLException: Incorrect string value: '\xE2\x96\x8A\xE2\x97\xA5...' for column 'data' at row 1
Query is: INSERT INTO AS_Container (x, y, z, world, type, slot, cause, id, count, data, time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);, parameters [-30,65,-173,20,5,6,272,587,1,'{"v": 2,"u": {"generation": 3,"pages": ["{\"extra\":[{\"bold\":true,\"italic\":true,\"text\":\"Animals\"},{\"bold\":true,\"color\":\"reset\",\"text\":\"\\n\"},{\"bold\":true,\"obfuscated\":true,\"text\":\"adsfadsf\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" \"},{\"bold\":true,\"obfuscated\":true,\"text\":\"fdswaf\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" \"},{\"bold\":true,\"obfuscated\":true,\"text\":\"alle asdfasdf\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" \"},{\"bold\":true,\"obfuscated\":true,\"text\":\"uww\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" \"},{\"bold\":true,\"obfuscated\":true,\"text\":\"asdf\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" warm\\n\"},{\"bold\":true,\"obfuscated\":true,\"text\":\"dssdf\"},{\"bold\":true,\"color\":\"reset\",\"text\":\" \"},{\"bold\":true,\"obfuscated\":true,\"text...
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:         at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:         at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212)
[20:33:18] [pool-3-thread-41/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:         ... 13 more
```

Full list of occurrences is here: https://gist.github.com/LemADEC/9453610ce52ff6d9a50275f79e60149c

Exact steps to reproduce are unknown at this time.

**Comment by Karanum** [comment]
What type of database are you using, and what is the character encoding for the database? This issue usually comes from using a character encoding that doesn't recognize certain special characters.

**Comment by LemADEC** [comment]
It's with MariaDB. The collation defaults to Swedish `latin1_swedish_ci`, I've manually changed it for AS tables and fields to be `utf8_general_ci`.
Sounds like the table creation scripts don't specify an explicit collation.
