### ISSUE TITLE
Not Working? - Log Posted

### ISSUE THREAD

**Issue by Vuhx** [Karanum/AdamantineShield#41]
18.11 09:51:29 [Server] Startup [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=adamantineshield, name=AdamantineShield, version=0.4.0, description=Action logging and rollback plugin for Sponge, authors=[Karanum, Snootiful], source=./mods/AdamantineShield-0.4.0.jar}
18.11 09:51:29 [Server] Startup com.google.common.util.concurrent.UncheckedExecutionException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)
18.11 09:51:29 [Server] Startup at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[minecraft_server.1.12.2.jar:?]
18.11 09:51:29 [Server] Startup at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[minecraft_server.1.12.2.jar:?]
18.11 09:51:29 [Server] Startup at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[minecraft_server.1.12.2.jar:?]
18.11 09:51:29 [Server] Startup at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[minecraft_server.1.12.2.jar:?]
18.11 09:51:29 [Server] Startup at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:163) ~[SqlServiceImpl.class:1.12.2-2768-7.1.4]
18.11 09:51:29 [Server] Startup at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:144) ~[SqlServiceImpl.class:1.12.2-2768-7.1.4]
18.11 09:51:29 [Server] Startup at com.karanumcoding.adamantineshield.db.Database.<init>(Database.java:38) ~[Database.class:?]
18.11 09:51:29 [Server] Startup at com.karanumcoding.adamantineshield.AdamantineShield.onPreInit(AdamantineShield.java:76) ~[AdamantineShield.class:?]
18.11 09:51:29 [Server] Startup at org.spongepowered.common.event.listener.GamePreInitializationEventListener_AdamantineShield_onPreInit4.handle(Unknown Source) ~

**Comment by Vuhx** [comment]
I'm looking at 

"18.11 09:51:29 [Server] Startup [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=adamantineshield, name=AdamantineShield, version=0.4.0, description=Action logging and rollback plugin for Sponge, authors=[Karanum, Snootiful], source=./mods/AdamantineShield-0.4.0.jar}
18.11 09:51:29 [Server] Startup com.google.common.util.concurrent.UncheckedExecutionException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)"

Not sure what this even means, and why AdamantineShield isn't working.

**Comment by LemADEC** [comment]
your credentials are incorrect:
Failed to initialize pool: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused (Connection refused)"
